name: stone_payments
description: Package para integração com as maquininhas Stone
version: 0.1.1
homepage: https://github.com/Leleocastro/stone_payments

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.ltag.stone_payments
        pluginClass: StonePaymentsPlugin

